FROM ubuntu:latest

RUN apt-get update && apt-get install -y nodejs

WORKDIR /usr/src/app

COPY package.json package-lock.json tsconfig.json turbo.json ./

COPY apps/user-app/package.json ./user-app/package.json

RUN npm install
RUN npm run db:generate
RUN npm run build

CMD ["npm", "run", 'start-user-app']