name: Build Succeeds on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build the project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma db:generate

      - name: Run Build
        run: npm run build
